# Numpy Kütüphanesi

In [3]:
import numpy as n
not1=[45,85,95,70,66,35]
not2=[55,25,100,75,66,22]

not1_n=n.array(not1)
not2_n=n.array(not2)

ortalama=(not1_n+not2_n)/2
print (ortalama)

[50.  55.  97.5 72.5 66.  28.5]


In [4]:
import numpy as np
Byt2=np.array([[4,9,9,8],[3,5,7,7]])
print(Byt2)

[[4 9 9 8]
 [3 5 7 7]]


In [5]:
import numpy as np

arr = np.array([1,2,3,5,4])
max_value=np.amax(arr)
print(max_value)

5


In [18]:
import numpy as np

arr = np.array([[1,2,3,5,4],[4,6,7,8,10],[8,7,3,4,5]])
max_value=np.amax(arr,axis=-2)
print(max_value)

[ 8  7  7  8 10]


In [19]:
import numpy as np

arr = np.array([[1,2,3,5,4],[4,6,7,8,10],[8,7,3,4,5]])
max_value=np.amax(arr,axis=1, keepdims=True)
print(max_value)

[[ 5]
 [10]
 [ 8]]


In [26]:
import numpy as np

arr = np.array([[1,2,3,5,4],[4,6,7,8,10],[8,7,3,4,5]])
max_value=np.amax(arr, initial=12)
print(max_value)

12
